### ISSUE TITLE
[Suggestion]: A mode to disable voxel clouds

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/simple-clouds#58]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Basically, when the mesh is being created, instead of converting to voxel mesh, it could just be the regular mesh instead, which allows for slightly more realistic clouds. 

This would be a setting in the client, since it should only be for rendering

**Comment by nonamecrackers2** [comment]
Not going to be doing this since this would require some big reworks (I assume you are talking about a marching cubes implementation) which I don't want to go through with. They are meant to look voxel-ly and I feel marching cubes would make them look extra strange and out of place. Though this feature is entirely preference, it doesn't really fit with my vision for the mod.
